### ISSUE TITLE
Ajout d'un 2ème champs texte dans le bilan de contrôle

### ISSUE THREAD

**Issue by heligonSeb** [pebble-solutions/kn-app#36]
![image](https://user-images.githubusercontent.com/52566459/210979032-95f53d60-f5fe-442a-aab9-ffe6089a5bcb.png)

Ajouter après "Vos remarques complémentaires" un champs texte pour mettre les axes amélioration comme ci dessous.

![image](https://user-images.githubusercontent.com/52566459/210979462-500550c0-0fa0-49e2-8434-3b0d30b77e7a.png)

**Comment by Guillaume35** [comment]
Libellé du champ : Actions correctives proposées :
