### ISSUE TITLE
Ajouter la sélection du chantier sur un controle

### ISSUE THREAD

**Issue by Guillaume35** [pebble-solutions/kn-app#6]
Le chantier (projet) du contrôle doit pouvoir être sélectionné :

- Par le responsable lors de la plannification du contrôle (dans **Programmation**)
- Par le contrôleur lors du démarage du contrôle (dans **Contrôleur**)

**Comment by Guillaume35** [comment]
/api/projet/GET/list?in_production=1

**Comment by heligonSeb** [comment]
a voir pour l'affichage dans les menu item et dans le header de la collecte

**Comment by Guillaume35** [comment]
Ajouter la mention du chantier dans
- Les menu items
- Les Headband
- Le header de la collecte lui même
- La synthèse

**Comment by Guillaume35** [comment]
L'API /api/data/GET/collecte retourne désormais une clé `projet_label` qui contient le nom du projet. Il n'est pas nécessaire d'interrogrer la table projet manuellement.
